version: '2'
services:
  db:
    container_name: db
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: 'Password!12'
      ACCEPT_EULA: 'Y'
  myenterpriseblazor-app:
    image: myenterpriseblazor
    depends_on:
      - db
    build:
      context: ../
      dockerfile: src/MyEnterpriseBlazor/Dockerfile
    ports:
      - 80:80
